#
# Generated by RepositoryTask on 9/22/14 3:04 PM
#
# name = quattor_15.2.0
# owner = grid.support@lal.in2p3.fr
# url = http://yum.quattor.org/15.2.0
#

structure template repository/quattor_15.2.0;

'name' = 'quattor_15.2.0';
'owner' = 'grid.support@lal.in2p3.fr';
'protocols' = list(
	dict(
	'name',	'http',
	'url',	'http://yum.quattor.org/15.2.0'
	)
);
