#
# Generated by RepositoryTask on 12/19/13 4:39 PM
#
# name = site
# owner = grid_admin@listserv.vub.ac.be
# url = http://yum.iihe.ac.be/cb9/sl6_t2b
#

structure template repository/snapshot/site;

"name" = "site";
"owner" = "grid_admin@listserv.vub.ac.be";
"protocols" = list(
  nlist("name","http",
        "url","http://yum.iihe.ac.be/cb9/"+REPO_YUM_SNAPSHOT_DATE['sl6_t2b']+"/sl6_t2b")
);
