#
# Generated by RepositoryTask on 11/8/13 5:26 PM
#
# name = sl6_addons
# owner = grid_admin@listserv.vub.ac.be
# url = http://yum.iihe.ac.be/cb9/sl6_addons
#

structure template repository/snapshot/sl6_addons;

"name" = "sl6_addons";
"owner" = "grid_admin@listserv.vub.ac.be";
"protocols" = list(
  nlist("name","http",
        "url","http://yum.iihe.ac.be/cb9/"+REPO_YUM_SNAPSHOT_DATE['sl6_addons']+"/sl6_addons")
);

