#
# Generated by RepositoryTask on 5/22/13 1:15 PM
#
# name = sl6x_x86_64
# owner = grid_admin@listserv.vub.ac.be
# url = http://yum.iihe.ac.be/cb9/sl6x-x86_64/
#

structure template repository/snapshot/sl6x_x86_64;

"name" = "sl6x_x86_64";
"owner" = "grid_admin@listserv.vub.ac.be";
"protocols" = list(
  nlist("name","http",
        "url","http://yum.iihe.ac.be/cb9/"+REPO_YUM_SNAPSHOT_DATE['sl6x_x86_64']+"/sl6x-x86_64")
);